spring:
  datasource:
    password: '%letsgo%'
    url: jdbc:postgresql://localhost:5432/letsgotodisplay
    username: letsgo
    tomcat:
      connectionProperties: useUnicode=true;characterEncoding=utf-8;
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  data:
    rest:
      return-body-on-create: true
      return-body-on-update: true
app: 
  weather: 
    api: 
      key: 2154cbadaa3015485f10fff459f8d611    